const codepenCoder = [
  { name: "Adam Argyle", codepen: "argyleink", tags: ["CSS", "Animation"] },
  {
    name: "Adam Kuhn",
    codepen: "cobra_winfrey",
    tags: ["SVG", "CSS", "Animation"],
  },
  {
    name: "Adir Slutzki",
    codepen: "Adir-SL",
    tags: ["CSS", "SVG", "Animation"],
  },
  {
    name: "Agathe Cocco",
    codepen: "agathaco",
    tags: ["SVG", "CSS", "Animation", "GSAP"],
  },
  {
    name: "Alex McNerney",
    codepen: "ajm13",
    tags: ["Canvas", "Particles", "Generative"],
  },
  {
    name: "Alexandre Rivaux",
    codepen: "alexr4",
    tags: ["WebGL", "GLSL", "Animation", "Generative"],
  },
  {
    name: "al-ro",
    codepen: "al-ro",
    tags: ["Shaders", "GLSL", "Three.js", "Particles"],
  },
  {
    name: "Alvaro Montoro",
    codepen: "alvaromontoro",
    tags: ["CSS", "Game", "Animation"],
  },
  {
    name: "Amelia Bellamy-Royds",
    codepen: "AmeliaBR",
    tags: ["SVG", "CSS", "Animation"],
  },
  {
    name: "Ana Tudor",
    codepen: "thebabydino",
    tags: ["Animation", "Canvas", "Sass", "Javascript"],
  },
  {
    name: "AndyMan",
    codepen: "Manoylov",
    tags: ["Canvas", "Generative", "Creative Code", "GSAP"],
  },
  {
    name: "Anthony Dugois",
    codepen: "anthonydugois",
    tags: ["SVG", "Three.js", "Animation", "Javascript"],
  },
  {
    name: "Bali Balo",
    codepen: "bali_balo",
    tags: ["Canvas", "Animation", "CSS", "Javascript"],
  },
  { name: "Ben Evans", codepen: "ivorjetski", tags: ["CSS"] },
  {
    name: "Blake Bowen",
    codepen: "osublake",
    tags: ["Animation", "SVG", "GSAP", "GreenSock", "Canvas", "Javascript"],
  },
  { name: "Cami Williams", codepen: "cwillycs", tags: ["CSS"] },
  {
    name: "Cassie Evans",
    codepen: "cassie-codes",
    tags: ["CSS", "Animation", "GSAP", "SVG"],
  },
  { name: "Cassidy Williams", codepen: "cassidoo", tags: ["CSS", "Animation"] },
  {
    name: "Chris Coyier",
    codepen: "chriscoyier",
    tags: ["SVG", "CSS", "Animation", "Javascript"],
  },
  {
    name: "Chris Gannon",
    codepen: "chrisgannon",
    tags: ["SVG", "Animation", "GSAP"],
  },
  {
    name: "Chris Johnson",
    codepen: "jhnsnc",
    tags: ["SVG", "Animation", "Shader", "WebGL", "GLSL", "Javascript"],
  },
  {
    name: "Christina Gorton",
    codepen: "cgorton",
    tags: ["SVG", "Animation", "GSAP", "CSS"],
  },
  {
    name: "Christopher Wallis",
    codepen: "notoriousb1t",
    tags: ["Animation", "SVG", "Javascript"],
  },
  {
    name: "CJ Gammon",
    codepen: "cjgammon",
    tags: ["SVG", "Canvas", "Animation", "Three.js"],
  },
  {
    name: "Dan Wilson",
    codepen: "danwilson",
    tags: ["Animation", "CSS", "WAAPI"],
  },
  { name: "Daniel", codepen: "scorch", tags: ["Canvas", "SVG", "Particles"] },
  {
    name: "Daniel Del Core",
    codepen: "delcore92",
    tags: ["Three.js", "3D", "WebGL"],
  },
  {
    name: "Dave Whyte",
    codepen: "beesandbombs",
    tags: ["P5.js", "Animation", "Canvas", "Javascript"],
  },
  {
    name: "David DeSandro",
    codepen: "desandro",
    tags: ["Animation", "Canvas", "Game"],
  },
  {
    name: "David Khourshid",
    codepen: "davidkpiano",
    tags: ["Animation", "CSS"],
  },
  {
    name: "Diaco ML",
    codepen: "MAW",
    tags: ["Animation", "GSAP", "SVG", "Canvas", "Javascript"],
  },
  {
    name: "Dion Snoeijen",
    codepen: "octopus11",
    tags: ["Canvas", "Javascript", "Creative Code", "Generative"],
  },
  {
    name: "DPDK",
    codepen: "dpdknl",
    tags: ["WebGL", "Three.js", "Animation", "GSAP"],
  },
  { name: "Drew Dahlman", codepen: "DrewDahlman", tags: ["Canvas", "P5.js"] },
  {
    name: "Dudley Storey",
    codepen: "dudleystorey",
    tags: ["SVG", "CSS", "Animation", "Javascript"],
  },
  {
    name: "Eli Fitch",
    codepen: "elifitch",
    tags: ["Animation", "Three.js", "WebGL", "Canvas"],
  },
  {
    name: "Elior Tabeka",
    codepen: "eliortabeka",
    tags: ["SASS", "Animation", "Javascript", "Games", "Components"],
  },
  {
    name: "Elliot Geno",
    codepen: "pyrografix",
    tags: ["SVG", "GreenSock", "GSAP", "Animation"],
  },
  {
    name: "Eva Santos",
    codepen: "SoyEva",
    tags: ["Animation", "CSS", "SVG", "Javascript"],
  },
  {
    name: "Fabio Ottaviani",
    codepen: "supah",
    tags: ["Animation", "SVG", "Three.js"],
  },
  {
    name: "Gabi",
    codepen: "enxaneta",
    tags: ["Canvas", "Animation", "SVG", "CSS", "Javascript"],
  },
  {
    name: "Gerard Ferrandez",
    codepen: "ge1doot",
    tags: ["Canvas", "3D", "Physics", "Animation"],
  },
  {
    name: "Giana",
    codepen: "giana",
    tags: ["CSS", "Animation", "Sass", "Canvas", "Javascript", "Particles"],
  },
  {
    name: "Grant Skinner",
    codepen: "gskinner",
    tags: ["Canvas", "Javascript", "Particles", "3D", "CreateJS"],
  },
  {
    name: "GreenSock",
    codepen: "GreenSock",
    tags: ["GSAP", "SVG", "Animation", "GreenSock", "Javascript"],
  },
  {
    name: "Greg Hovanesyan",
    codepen: "gregh",
    tags: ["Javascript", "Web Audio", "Animation", "Game", "CSS"],
  },
  {
    name: "Hernan Torrisi",
    codepen: "airnan",
    tags: ["SVG", "Animation", "Canvas", "GSAP"],
  },
  {
    name: "Himalaya Singh",
    codepen: "himalayasingh",
    tags: ["CSS", "Animation"],
  },
  {
    name: "Hornebom",
    codepen: "Hornebom",
    tags: ["Animation", "CSS", "SVG", "Three.js"],
  },
  {
    name: "ilithya",
    codepen: "ilithya",
    tags: ["CSS", "Animation", "3D", "Javascript", "Shaders"],
  },
  {
    name: "Issey",
    codepen: "issey",
    tags: ["SVG", "Animation", "GreenSock", "GSAP"],
  },
  {
    name: "Jack Rugile",
    codepen: "jackrugile",
    tags: ["Canvas", "Animation", "CSS", "Particles", "Javascript"],
  },
  {
    name: "Jackson A. Joseph",
    codepen: "alexandrejosephdev",
    tags: ["3D", "Three.js", "Particles", "Animation", "CreativeCode"],
  },
  { name: "Jake Albaugh", codepen: "jakealbaugh", tags: ["CSS", "Web Audio"] },
  {
    name: "Jamie Coulter",
    codepen: "jcoulterdesign",
    tags: ["CSS", "Game", "Animation"],
  },
  {
    name: "Jatin Rao",
    codepen: "jatinrao",
    tags: ["CSS", "Javascript", "Animation"],
  },
  {
    name: "Jerome Herr",
    codepen: "p5art",
    tags: [
      "Canvas",
      "Animation",
      "P5js",
      "Particles",
      "Processing",
      "Generative",
    ],
  },
  {
    name: "Jhey Tompkins",
    codepen: "jh3y",
    tags: ["Animation", "CSS", "GreenSock", "SVG"],
  },
  {
    name: "Johan Karlsson",
    codepen: "DonKarlssonSan",
    tags: ["P5.js", "Fractal", "Canvas", "Animation", "WebAudio"],
  },
  {
    name: "Joni Trythall",
    codepen: "jonitrythall",
    tags: ["Animation", "SVG", "Sass"],
  },
  {
    name: "Joseph Rex",
    codepen: "josephrexme",
    tags: ["Animation", "GSAP", "SVG", "CSS"],
  },
  { name: "Judith Neumann", codepen: "judag", tags: ["Animation", "CSS"] },
  { name: "Julia Muzafarova", codepen: "miocene", tags: ["Animation", "CSS"] },
  {
    name: "Julian Garnier",
    codepen: "juliangarnier",
    tags: ["Animation", "SVG", "CSS", "3D", "Javascript"],
  },
  {
    name: "Justin Windle",
    codepen: "soulwire",
    tags: [
      "Animation",
      "Canvas",
      "Particles",
      "Physics",
      "Javascript",
      "WebGL",
    ],
  },
  {
    name: "K-T",
    codepen: "K-T",
    tags: ["Animation", "Canvas", "Particles", "Javascript"],
  },
  {
    name: "Kass",
    codepen: "kassandrasanch",
    tags: ["CSS", "GSAP"],
  },
  {
    name: "Karim Maaloul",
    codepen: "Yakudoo",
    tags: ["Animation", "WebGL", "Three.js", "3D", "Particles", "GSAP"],
  },
  {
    name: "Kenji Saito",
    codepen: "kenjiSpecial",
    tags: ["Animation", "Canvas", "WebGL", "Three.js", "Particle", "Shader"],
  },
  {
    name: "Kevin LEVRON",
    codepen: "soju22",
    tags: ["WebGL", "Three.js", "SVG"],
  },
  {
    name: "Kyle Brumm",
    codepen: "kjbrum",
    tags: ["Animation", "CSS", "Javascript"],
  },
  {
    name: "Lea Rosema",
    codepen: "terabaud",
    tags: ["WebGL", "GLSL", "SVG", "Canvas", "CSS"],
  },
  {
    name: "LegoMushroom",
    codepen: "sol0mka",
    tags: ["Animation", "Javascript", "SVG", "Canvas"],
  },
  {
    name: "Liam Brummitt",
    codepen: "liabru",
    tags: ["Animation", "Canvas", "Physics"],
  },
  {
    name: "Liam Egan",
    codepen: "shubniggurath",
    tags: [
      "GLSL",
      "Shaders",
      "Javascript",
      "Generative",
      "CreativeCode",
      "Animation",
    ],
  },
  {
    name: "Lisi",
    codepen: "lisilinhart",
    tags: ["Animation", "SVG", "GSAP", "CSS"],
  },
  {
    name: "Louis Hoebregts",
    codepen: "Mamboleoo",
    tags: ["Canvas", "Three.js", "Particles", "Shader", "GSAP", "Animation"],
  },
  {
    name: "Lucas Bebber",
    codepen: "lbebber",
    tags: ["CSS", "Animation", "SVG"],
  },
  {
    name: "Mandy Michael",
    codepen: "mandymichael",
    tags: ["CSS", "Effects", "Animation"],
  },
  {
    name: "Marco Dell´Anna",
    codepen: "plasm",
    tags: ["Animation", "Particles", "GreenSock"],
  },
  {
    name: "Mariusz Dabrowski",
    codepen: "MarioD",
    tags: ["Animation", "SVG", "Canvas", "Physics", "P5.js", "GSAP"],
  },
  { name: "Massimo", codepen: "_massimo", tags: ["Canvas", "CSS", "SVG"] },
  {
    name: "masuwa",
    codepen: "ma_suwa",
    tags: ["PostProcessing", "Three.js", "GLSL", "Canvas", "Shader"],
  },
  {
    name: "Mattia Astorino",
    codepen: "equinusocio",
    tags: ["CSS", "Animation", "Creative Code"],
  },
  {
    name: "Michael Gehrmann",
    codepen: "g12n",
    tags: ["CSS", "SVG", "Animation"],
  },
  {
    name: "Mike Schultz",
    codepen: "mike-schultz",
    tags: ["Animation", "SVG", "CSS"],
  },
  {
    name: "Mustafa Enes",
    codepen: "pavlovsk",
    tags: ["CSS", "Animation", "CSS"],
  },
  {
    name: "Nat Cooper",
    codepen: "natacoops",
    tags: ["SVG", "Animation", "CSS", "GSAP"],
  },
  {
    name: "Noel Delgado",
    codepen: "noeldelgado",
    tags: ["Animation", "Canvas", "CSS", "SVG"],
  },
  {
    name: "Not Important",
    codepen: "clindsey",
    tags: ["Animation", "Canvas", "Three.js", "Javascript"],
  },
  {
    name: "Olivia",
    codepen: "oliviale",
    tags: ["Animation", "CSS", "Javascript"],
  },
  {
    name: "Paul J Karlik",
    codepen: "pjkarlik",
    tags: ["Animation", "WebGL", "GLSL", "Canvas", "Shader", "Three.js"],
  },
  {
    name: "Peter Barr",
    codepen: "petebarr",
    tags: ["Animation", "SVG", "GSAP", "CSS", "GreenSock"],
  },
  {
    name: "Petr Tichy",
    codepen: "ihatetomatoes",
    tags: ["CSS", "Animation", "GreenSock", "SVG", "GSAP", "Canvas"],
  },
  {
    name: "Ricardo Oliva Alonso",
    codepen: "ricardoolivaalonso",
    tags: ["CSS", "Animation"],
  },
  { name: "Rachel Bull", codepen: "rachel_web", tags: ["CSS", "Animation"] },
  {
    name: "Rachel Nabors",
    codepen: "rachelnabors",
    tags: ["Animation", "CSS", "SVG", "WAAPI"],
  },
  {
    name: "Rachel Smith",
    codepen: "rachsmith",
    tags: ["Animation", "Canvas", "SVG", "Particles", "WebGL"],
  },
  {
    name: "Riley J Shaw",
    codepen: "rileyjshaw",
    tags: ["Animation", "Canvas", "CSS", "Javascript"],
  },
  {
    name: "Rob DiMarzo",
    codepen: "robdimarzo",
    tags: ["Animation", "Canvas", "CSS", "Javascript", "GSAP"],
  },
  {
    name: "Ryan Thavi",
    codepen: "rthavi",
    tags: ["Generative", "Canvas", "Animation", "Javascript"],
  },
  {
    name: "Sasha Tran",
    codepen: "sashatran",
    tags: ["CSS", "SVG", "Animation"],
  },
  {
    name: "Sara Soueidan",
    codepen: "SaraSoueidan",
    tags: ["SVG", "CSS", "Animation"],
  },
  {
    name: "Sarah Drasner",
    codepen: "sdras",
    tags: ["Animation", "SVG", "Javascript", "GreenSock", "GSAP", "Canvas"],
  },
  { name: "Sarah Fossheim", codepen: "fossheim", tags: ["CSS", "Animation"] },
  {
    name: "Sebastian DeRossi",
    codepen: "derossi_s",
    tags: ["Create.JS", "Easel.JS", "Canvas", "Animation", "Javascript"],
  },
  {
    name: "Stívali Serna",
    codepen: "stivaliserna",
    tags: ["3D", "Three.js", "Animation", "CSS"],
  },
  {
    name: "Scott R McGann",
    codepen: "cantelope",
    tags: ["Animation", "Canvas", "3D", "Particles", "Javascript"],
  },
  {
    name: "Shaw",
    codepen: "shshaw",
    tags: ["Animation", "CSS", "SVG", "Javascript", "Canvas", "Three.js"],
  },
  {
    name: "Stefan Weck",
    codepen: "stefanweck",
    tags: ["Canvas", "Animation", "WebGL", "Shader"],
  },
  {
    name: "Sullivan Nolan",
    codepen: "nolakat",
    tags: ["Animation", "CSS", "SVG", "WebGL"],
  },
  {
    name: "Szenia Zadvornykh",
    codepen: "zadvorsky",
    tags: ["Canvas", "Three.js", "WebGL", "Shader"],
  },
  {
    name: "Takashi",
    codepen: "tksiiii",
    tags: ["P5.js", "Canvas", "Particles"],
  },
  { name: "Tee Diang", codepen: "cybercountess", tags: ["CSS", "Animaiton"] },
  {
    name: "Tibix",
    codepen: "Tibixx",
    tags: ["Animation", "Canvas", "CSS", "Particles"],
  },
  {
    name: "Tim Holman",
    codepen: "tholman",
    tags: ["Canvas", "Animation", "Interactive", "Generative", "JS"],
  },
  {
    name: "Thepheer",
    codepen: "thepheer",
    tags: ["Canvas", "Particles", "3D", "WebGL", "Shader"],
  },
  {
    name: "Thibaut",
    codepen: "Thibka",
    tags: ["Canvas", "Particles", "Three.js", "Animation"],
  },
  {
    name: "Tiffany Rayside",
    codepen: "tmrDevelops",
    tags: ["Animation", "Canvas", "Particles", "SVG", "CSS"],
  },
  {
    name: "Toshiya Marukubo",
    codepen: "toshiya-marukubo",
    tags: ["Animation", "Canvas", "Javascript", "Particles"],
  },
  {
    name: "Val Head",
    codepen: "valhead",
    tags: ["Animation", "CSS", "SVG", "P5.js", "GreenSock"],
  },
  {
    name: "Varun Vachhar",
    codepen: "winkerVSbecks",
    tags: ["Animation", "CSS", "SVG", "P5.js", "GreenSock", "GSAP"],
  },
  {
    name: "Victor Vergara",
    codepen: "vcomics",
    tags: ["3D", "Three.js", "Shader", "Animation"],
  },
  { name: "Yoksel", codepen: "yoksel", tags: ["Animation", "CSS", "SVG"] },
  {
    name: "Yuán Chuān",
    codepen: "yuanchuan",
    tags: ["SVG", "CSS", "Animation", "GreenSock", "Javascript"],
  },
  {
    name: "Yugam Dhuriya",
    codepen: "pizza3",
    tags: ["Animation", "CSS", "SVG", "Canvas", "P5.js"],
  },
  {
    name: "Yusuke Nakaya",
    codepen: "YusukeNakaya",
    tags: ["Animation", "CSS"],
  },
  {
    name: "Zach Saucier",
    codepen: "Zeaklous",
    tags: ["Animation", "CSS", "SVG"],
  },
  { name: "Zed Dash", codepen: "z-", tags: ["Animation", "CSS", "Javascript"] },
];
module.exports = codepenCoder;
